---
# tasks file for nginx

- name: Move the Repo RPM over to the box
  sudo: yes
  copy: "src=nginx-centos-{{ centos_version | default('7') }}.rpm dest=/tmp/nginx-centos-{{ centos_version | default('7') }}.rpm mode=755"
  tags: nginx

- name: Install Repo RPM
  sudo: yes
  yum: "name=/tmp/nginx-centos-{{ centos_version | default('7') }}.rpm state=present"
  tags: nginx

- name: Install NGINX Dependencies
  sudo: yes
  yum: "name={{ item }} state=present enablerepo=nginx"
  with_items: nginx.dependencies
  tags: nginx

- name: Install NGINX Packages
  sudo: yes
  yum: "name={{ item }} state=present"
  with_items: nginx.packages
  tags: nginx

- name: Create the directories for site specific configurations
  sudo: yes
  tags: nginx
  file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"

- name: Copy the nginx configuration file
  sudo: yes
  tags: nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
  - Reload NGINX

- name: Copy the nginx default configuration file
  sudo: yes
  tags: nginx
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify:
  - Reload NGINX

- name: Create the configurations for sites
  sudo: yes
  tags:
  - nginx
  - nginx_virtualhosts
  template: "src=site.conf.j2 dest=/etc/nginx/sites-available/{{ item['file_name'] }}.conf"
  with_items: nginx_sites
  when: nginx_sites|lower is defined
  notify:
  - Reload NGINX

- name: Create the link for site enabled specific configurations
  sudo: yes
  tags:
  - nginx
  - nginx_virtualhosts
  file: "path=/etc/nginx/sites-enabled/{{ item['file_name'] }}.conf state=link src=/etc/nginx/sites-available/{{ item['file_name'] }}.conf"
  with_items: nginx_sites
  when: nginx_sites is defined
  notify:
  - Reload NGINX

- name: start the nginx service
  sudo: yes
  tags: nginx
  service: name=nginx state=started enabled=yes
