---

- name: Move the Repo RPM over to the box
  copy: "src=nginx-centos-{{ centos_version | default('7') }}.rpm dest=/tmp/nginx-centos-{{ centos_version | default('7') }}.rpm mode=755"
  tags: nginx

- name: Install Repo RPM
  yum: "name=/tmp/nginx-centos-{{ centos_version | default('7') }}.rpm state=present"
  tags: nginx

- name: Install NGINX Dependencies
  yum: "name={{ item }} state=present enablerepo=nginx"
  with_items: "{{ nginx.dependencies }}"
  tags: nginx

- name: Install NGINX Packages
  yum: "name={{ item }} state=present"
  with_items: "{{ nginx.packages }}"
  tags: nginx
